all: protoulis_7968_interactive protoulis_7968_batch myshell

protoulis_7968_interactive: protoulis_7968_interactive.c
	cc -o protoulis_7968_interactive protoulis_7968_interactive.c

protoulis_7968_batch: protoulis_7968_batch.c
	cc -o protoulis_7968_batch protoulis_7968_batch.c 

myshell: myshell.c
	cc -o myshell myshell.c
